import type { CloudFile, CloudAccount, Tag, User, Activity, UploadItem } from '../types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Min Kaung',
  email: 'min@example.com',
  avatar: 'M',
  createdAt: '2026-01-15T08:00:00Z',
};

export const mockAccounts: CloudAccount[] = [
  {
    id: 'acc-1',
    provider: 'google-drive',
    email: 'min.work@gmail.com',
    label: 'Work Drive',
    storageUsed: 12.4 * 1024 * 1024 * 1024,
    storageTotal: 15 * 1024 * 1024 * 1024,
    status: 'connected',
    lastSyncedAt: '2026-10-25T14:30:00Z',
  },
  {
    id: 'acc-2',
    provider: 'google-drive',
    email: 'min.personal@gmail.com',
    label: 'Personal Drive',
    storageUsed: 3.8 * 1024 * 1024 * 1024,
    storageTotal: 15 * 1024 * 1024 * 1024,
    status: 'syncing',
    lastSyncedAt: '2026-10-25T14:28:00Z',
  },
  {
    id: 'acc-3',
    provider: 'dropbox',
    email: 'min@dropbox.com',
    label: 'Dropbox',
    storageUsed: 1.2 * 1024 * 1024 * 1024,
    storageTotal: 2 * 1024 * 1024 * 1024,
    status: 'connected',
    lastSyncedAt: '2026-10-25T13:00:00Z',
  },
  {
    id: 'acc-4',
    provider: 'onedrive',
    email: 'min@outlook.com',
    label: 'OneDrive',
    storageUsed: 0.5 * 1024 * 1024 * 1024,
    storageTotal: 5 * 1024 * 1024 * 1024,
    status: 'error',
    lastSyncedAt: '2026-10-24T10:00:00Z',
  },
];

export const mockTags: Tag[] = [
  { id: 'tag-1', name: 'Work', color: 'bg-blue-500' },
  { id: 'tag-2', name: 'Personal', color: 'bg-green-500' },
  { id: 'tag-3', name: 'Design', color: 'bg-amber-500' },
  { id: 'tag-4', name: 'Archive', color: 'bg-zinc-500' },
];

export const mockFiles: CloudFile[] = [
  {
    id: 'folder-1',
    name: 'Design Projects',
    mimeType: 'application/vnd.google-apps.folder',
    size: 0,
    isFolder: true,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-22T09:30:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: [],
  },
  {
    id: 'folder-2',
    name: 'Documents',
    mimeType: 'application/vnd.google-apps.folder',
    size: 0,
    isFolder: true,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-20T14:15:00Z',
    thumbnail: null,
    isFavorite: true,
    tags: ['Work'],
  },
  {
    id: 'folder-3',
    name: 'Photos',
    mimeType: 'application/vnd.google-apps.folder',
    size: 0,
    isFolder: true,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-2',
    modifiedTime: '2026-10-18T11:00:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Personal'],
  },
  {
    id: 'folder-4',
    name: 'Shared with Team',
    mimeType: 'application/vnd.google-apps.folder',
    size: 0,
    isFolder: true,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-24T08:00:00Z',
    thumbnail: null,
    isFavorite: true,
    tags: ['Work'],
  },
  {
    id: 'file-1',
    name: 'CloudHub_Architecture.pdf',
    mimeType: 'application/pdf',
    size: 2516582,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-24T10:15:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Work'],
  },
  {
    id: 'file-2',
    name: 'UI_Mockups_Final.fig',
    mimeType: 'application/x-figma',
    size: 45123892,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-25T14:32:00Z',
    thumbnail: null,
    isFavorite: true,
    tags: ['Design'],
  },
  {
    id: 'file-3',
    name: 'Q3_Budget_Report.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 856320,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-23T16:45:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Work'],
  },
  {
    id: 'file-4',
    name: 'meeting_notes_oct.md',
    mimeType: 'text/markdown',
    size: 12480,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-25T09:10:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: [],
  },
  {
    id: 'file-5',
    name: 'presentation_deck.pptx',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size: 8934400,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-1',
    modifiedTime: '2026-10-21T13:20:00Z',
    thumbnail: null,
    isFavorite: true,
    tags: ['Work', 'Design'],
  },
  {
    id: 'file-6',
    name: 'logo_final_v3.svg',
    mimeType: 'image/svg+xml',
    size: 34200,
    isFolder: false,
    parentId: null,
    provider: 'dropbox',
    cloudAccountId: 'acc-3',
    modifiedTime: '2026-10-19T17:55:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Design'],
  },
  {
    id: 'file-7',
    name: 'backup_config.json',
    mimeType: 'application/json',
    size: 2048,
    isFolder: false,
    parentId: null,
    provider: 'dropbox',
    cloudAccountId: 'acc-3',
    modifiedTime: '2026-10-17T08:30:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Archive'],
  },
  {
    id: 'file-8',
    name: 'vacation_photo_001.jpg',
    mimeType: 'image/jpeg',
    size: 4521984,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-2',
    modifiedTime: '2026-10-15T20:10:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Personal'],
  },
  {
    id: 'file-9',
    name: 'family_trip_video.mp4',
    mimeType: 'video/mp4',
    size: 256000000,
    isFolder: false,
    parentId: null,
    provider: 'google-drive',
    cloudAccountId: 'acc-2',
    modifiedTime: '2026-10-14T18:00:00Z',
    thumbnail: null,
    isFavorite: true,
    tags: ['Personal'],
  },
  {
    id: 'file-10',
    name: 'tax_return_2025.pdf',
    mimeType: 'application/pdf',
    size: 1234567,
    isFolder: false,
    parentId: null,
    provider: 'onedrive',
    cloudAccountId: 'acc-4',
    modifiedTime: '2026-10-10T12:00:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Personal', 'Archive'],
  },
  {
    id: 'file-11',
    name: 'sprint_retro_notes.md',
    mimeType: 'text/markdown',
    size: 8200,
    isFolder: false,
    parentId: null,
    provider: 'dropbox',
    cloudAccountId: 'acc-3',
    modifiedTime: '2026-10-22T11:45:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Work'],
  },
  {
    id: 'file-12',
    name: 'api_keys.env',
    mimeType: 'text/plain',
    size: 512,
    isFolder: false,
    parentId: null,
    provider: 'onedrive',
    cloudAccountId: 'acc-4',
    modifiedTime: '2026-10-20T09:00:00Z',
    thumbnail: null,
    isFavorite: false,
    tags: ['Archive'],
  },
];

export const mockActivities: Activity[] = [
  { id: 'act-1', type: 'upload', fileName: 'UI_Mockups_Final.fig', provider: 'google-drive', timestamp: '2026-10-25T14:32:00Z', description: 'Uploaded to Work Drive' },
  { id: 'act-2', type: 'rename', fileName: 'Q3_Budget_Report.xlsx', provider: 'google-drive', timestamp: '2026-10-23T16:50:00Z', description: 'Renamed from "budget_q3.xlsx"' },
  { id: 'act-3', type: 'download', fileName: 'logo_final_v3.svg', provider: 'dropbox', timestamp: '2026-10-23T15:00:00Z', description: 'Downloaded from Dropbox' },
  { id: 'act-4', type: 'share', fileName: 'presentation_deck.pptx', provider: 'google-drive', timestamp: '2026-10-22T10:00:00Z', description: 'Shared with team@company.com' },
  { id: 'act-5', type: 'favorite', fileName: 'Documents', provider: 'google-drive', timestamp: '2026-10-21T09:00:00Z', description: 'Added to favorites' },
  { id: 'act-6', type: 'delete', fileName: 'old_backup.zip', provider: 'dropbox', timestamp: '2026-10-20T17:30:00Z', description: 'Deleted from Dropbox' },
  { id: 'act-7', type: 'move', fileName: 'CloudHub_Architecture.pdf', provider: 'google-drive', timestamp: '2026-10-20T14:00:00Z', description: 'Moved to Documents' },
  { id: 'act-8', type: 'sync', fileName: '', provider: 'google-drive', timestamp: '2026-10-20T08:00:00Z', description: 'Synced Work Drive — 142 files updated' },
  { id: 'act-9', type: 'upload', fileName: 'backup_config.json', provider: 'dropbox', timestamp: '2026-10-17T08:30:00Z', description: 'Uploaded to Dropbox' },
  { id: 'act-10', type: 'sync', fileName: '', provider: 'onedrive', timestamp: '2026-10-16T10:00:00Z', description: 'Synced OneDrive — 23 files updated' },
];

export const mockUploadItems: UploadItem[] = [
  { id: 'upl-1', fileName: 'new_design_v2.fig', size: 32000000, progress: 100, status: 'complete', targetAccountId: 'acc-1' },
  { id: 'upl-2', fileName: 'quarterly_analysis.xlsx', size: 1200000, progress: 65, status: 'uploading', targetAccountId: 'acc-1' },
  { id: 'upl-3', fileName: 'team_photo.png', size: 5400000, progress: 30, status: 'uploading', targetAccountId: 'acc-3' },
  { id: 'upl-4', fileName: 'corrupted_file.dat', size: 800000, progress: 12, status: 'error', targetAccountId: 'acc-4' },
  { id: 'upl-5', fileName: 'readme.md', size: 4096, progress: 0, status: 'pending', targetAccountId: 'acc-1' },
];
